### ISSUE TITLE
Decide what minimum versions of django/python DAT should support

### ISSUE THREAD

**Issue by izimobil** [django-admin-tools/django-admin-tools#1]
At the moment DAT supports django 1.3 to django 1.7, to ease development and clean up things we should decide what minimum versions the next release should support.

Personally I would vote for django >= 1.7 (mainly because of the new migration system) and python 2.7 or python 3.

Older projects can still use DAT 0.5.2.

What do you think ?

**Comment by yakky** [comment]
@izimobil :+1:

**Comment by andybak** [comment]
I suppose I'd argue that we support as many versions as we can without it being a burden. 

So we can keep move existing migrations into a south_migrations directory and South>=1.0 will automatically do the right thing. Maybe when we need new migrations we can decide whether it's worth the effort of generating South-style or whether we drop support at that point.

Another project that can really ease the burden of supporting older versions is https://github.com/arteria/django-compat which I think is being considered for official blessing.

**Comment by izimobil** [comment]
While I'm usually in favor of not breaking BC, I would prefer if we give DAT a fresh start without the problems of the past (if you look at the bitbucket issues, a lot of them are related to django version compatibility).

Also, django official support for 1.4, 1.5 and 1.6 will end very soon, so I'm not sure it's worth adding a dependency.

**Comment by andybak** [comment]
Sounds sensible

**Comment by shtalinberg** [comment]
django >= 1.7
Older projects can still use DAT 0.5.2.
:+1:

**Comment by andybak** [comment]
From: https://groups.google.com/forum/#!topic/django-developers/MTvOPDNQXLI

Q: I’m the maintainer of a reusable application. Which Django versions should I support?
A: We recommend that you support the same Django versions that are supported by the Django team. With the new deprecation policy, it should be possible to support two consecutive LTS releases (e.g. 1.8 and 2.1) and all the non-LTS versions in between without requiring backwards-compatibility shims in your own code, as long as your code runs warning-clean on the lower LTS (1.8), because any non-deprecated feature in one LTS release is guaranteed to remain in place through the next LTS release.

**Comment by anrie** [comment]
A new DAT version that requires at least Django 1.7 and switches to the new migrations sounds like the way to go!

**Comment by izimobil** [comment]
Closing this issue. Compatibility django >= 1.7 seems to be the consensus.
