### ISSUE TITLE
Update to a secure version of jquery-ui (1.12.1)

### ISSUE THREAD

**Issue by RobinRamael** [django-admin-tools/django-admin-tools#82]
The jquery-ui version currently used by admin-tools is vulnerable to XSS exploits (see: https://snyk.io/vuln/npm:jquery-ui:20160721). Would it be difficult to update this? 

I have a fork of admin-tools with the update which seems to be working for our use cases, which i can open a PR for, but I can't say I have enough experience with jQuery to be sure that simply bumping the version would not break anything else in the tools.

**Comment by izimobil** [comment]
Hi, thanks for your report.

DAT is not affected by this issue as we only use jquery-ui for the sortable() functionality (in order to drag'n'drop dashboard modules), we should eventually find another small library and get rid of jquery-ui someday.

I'm keeping this opened as a reminder to clean up dependencies.

**Comment by izimobil** [comment]
Fixed in 0.9.1
